name: Quality assurance
on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        php-version: ['5.5', '8.1']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2, psalm
          coverage: none
      - name: Install dependencies
        run: composer install
      - name: Run static analysis
        run: psalm --output-format=github
