name: Quality assurance
on:
  push:
  pull_request:

jobs:
  legacy-tests:
    runs-on: ubuntu-latest
    container:
      image: feitosa/php55-with-composer
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit

  modern-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: vendor/bin/phpunit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '5.5'
          tools: composer:v2,parallel-lint
          coverage: none
      - name: Install dependencies
        run: composer install
      - name: Lint PHP files
        run: parallel-lint src tests
